# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_calendar', '0008_timetable_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studyGroup',
            field=models.ManyToManyField(to='study_calendar.StudyGroup'),
        ),
    ]
