# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_calendar', '0005_auto_20161017_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='table',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='owner_group',
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
