# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_calendar', '0007_auto_20161017_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(default='main', max_length=255),
        ),
    ]
